//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer30028452
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer30028452()
        {
            this.Orders30028452 = new HashSet<Orders30028452>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string CType { get; set; }
        public string CardNo { get; set; }
        public string Email { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders30028452> Orders30028452 { get; set; }
    }
}
