//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieOrders30028452
    {
        public int OrderId { get; set; }
        public int MovieId { get; set; }
    
        public virtual Orders30028452 Orders30028452 { get; set; }
    }
}
